---
title: "BA"
author: "Patrick Bigler"
date: "2023-07-07"
output: html_document
---

# Introduction

## Read packages

```{r message=FALSE, error=FALSE, warning=FALSE}
source("../R/General/packages.R")

conflicts_prefer(ggplot2::annotate)
```

## Read files

```{r}
Montezuma.1920.1930 <- read.delim("../Data/Montezuma.txt")

Harqua_Hala.1920.1925 <- read.delim("../Data/Harqua_Hala.txt")

Mt.Wilson.1905.1920 <- read.delim("../Data/Mt_Wilson_1.txt")

Mt.Wilson.1905.1906 <- read.delim("../Data/Mt_Wilson_2.txt")

Mt.Wilson.1909.1912 <- read.delim("../Data/Mt_Wilson_3.txt")

Washington.1902.1904 <- read.delim("../Data/Washington_1.txt")

Washington.1903.1907 <- read.delim("../Data/Washington_2.txt")

Bassour.1911.1912 <- read.delim("../Data//Bassour.txt")

Hump_Mountain.1917.1918 <- read.delim("../Data/Hump_Mountain.txt")

Calama.1918.1920 <- read.delim("../Data/Calama.txt")

Mounth.Whitney.1909.1910 <- read.delim("../Data/Mounth_Whitney.txt")

Mt.Brukkaros.1926.1930 <- read.delim("../Data/Mt_Brukkaros.txt")

Table.mountain.1925.1930 <- read.delim("../Data/Table_mountain.txt")
```

## Coordinates-Transformation

```{r}
source("../R/function.coordinate.transformation.R")
Katmai.lat <- coordinates.transfomation(58, 16, 43)
Katmai.lon <- coordinates.transfomation(-154, -57, -24.9)

Santa.Maria.lat <- coordinates.transfomation(14, 45, 20)
Santa.Maria.lon <- coordinates.transfomation(-91, -33, -6)

katla.lat <- coordinates.transfomation(63, 37, 50)
katla.lon <- coordinates.transfomation(-19, -3, -0)

ksudach.lat <- coordinates.transfomation(51, 48, 26)
ksudach.lon <- coordinates.transfomation(157, 32, 3)

raikoke.lat <- coordinates.transfomation(48, 17, 30)
raikoke.lon <- coordinates.transfomation(153, 14, 30)

Montezuma.lat <- coordinates.transfomation(-22, -40, -0)
Montezuma.lon <- coordinates.transfomation(-68, -56, -0)

Calama.lat <- coordinates.transfomation(-22, -28, -0)
Calama.lon <- coordinates.transfomation(-68, -56, -0)

Table.Mountain.lat <- coordinates.transfomation(34, 22, 0)
Table.Mountain.lon <- coordinates.transfomation(-117, -41, -0)

Harqua.Hala.lat <- coordinates.transfomation(33, 48, 0)
Harqua.Hala.lon <- coordinates.transfomation(-113, -20, 0)

Mount.Brukkaros.lat <- coordinates.transfomation(-25, -52, -0)
Mount.Brukkoras.lon <- coordinates.transfomation(17, 48, 0)

Mount.Whitney.lat <- coordinates.transfomation(36, 34, 44)
Mount.Whitney.lon <- coordinates.transfomation(-118, -17, -29)

Mount.Wilson.lat <- coordinates.transfomation(34, 12, 55)
Mount.Wilson.lon <- coordinates.transfomation(-118, -17, -29)

Washington.lat <- coordinates.transfomation(38, 53, 17.3)
Washingtons.lon <- coordinates.transfomation(-77, -01, -33.6)

Hump.Mountain.lat <- coordinates.transfomation(36, 8, 0)
Hump.Mountain.lon <- coordinates.transfomation(-82, 0, 0)

Bassour.lat <- coordinates.transfomation(36, 13, 0)
Bassour.lon <- coordinates.transfomation(2, 51, 30)
```

## Create a tibble

```{r}
df.locations <- tibble("Location" =
c("Katmai", "Santa Maria", "Katla", "Ksudach", "Raikoke", "Montezuma",
"Calama", "Table Mountain", "Harqua Hala",
"Mt. Brukkaros","Mt. Whitney", "Mt. Wilson",
"Washington","Hump Mountain", "Bassour"),
"latitude" =
c(Katmai.lat, Santa.Maria.lat, katla.lat, ksudach.lat, raikoke.lat, Montezuma.lat,
Calama.lat, Table.Mountain.lat, Harqua.Hala.lat,
Mount.Brukkaros.lat,Mount.Whitney.lat,
Mount.Wilson.lat, Washington.lat,
Hump.Mountain.lat, Bassour.lat),
"longitude" =
c(Katmai.lon, Santa.Maria.lon, katla.lon , ksudach.lon, raikoke.lon , Montezuma.lon,
Calama.lon, Table.Mountain.lon, Harqua.Hala.lon,
Mount.Brukkoras.lon, Mount.Whitney.lon,
Mount.Wilson.lon, Washingtons.lon,
Hump.Mountain.lon, Bassour.lon),
"Altitude" =
c(2047, 3772, 1512, 1079, 551, 2711, 2250, 2286, 1721,
1586, 4420, 1727, 10, 2250, 1160),
"Legend" =
c(rep("Volcano",5), rep("Observation station", 10)))
```

## Visualize the overview

```{r}
library(ggrepel)
#read the world map
world_map <- map_data("world")
# map the locations
pdf('../analysis/map.pdf',
    width = 8, height = 5)
ggplot() +
geom_map(data = world_map, map = world_map,
aes(long, lat, map_id = region),
color = "white", fill = "lightgray", size = 0.1) +
geom_point(data = df.locations, aes(x = `longitude`, y = `latitude`,
color = Legend), size = 0.5) +
scale_y_continuous(limits = c(-80, 80)) +
scale_x_continuous(limits = c(-180, 180)) +
labs(x = "Longitude [deg]", y = "Latitude [deg]") +
theme_light() +
geom_label_repel(aes(x = df.locations$longitude, y = df.locations$latitude ,
label = df.locations$Location, color = df.locations$Legend,
size = NULL), box.padding   = 0.35, point.padding = 0.5,
segment.color = 'grey50', max.overlaps = 100, show.legend = FALSE) +
theme(legend.background = element_rect(fill = "white", size = 0.5, 
                                       linetype = "solid", colour = "black")) +
theme(legend.position = c(.02, .035),
      legend.justification = c("left", "bottom"), legend.box.just = "right",
      legend.margin = margin(6, 6, 6, 6)) +
theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```

# Analysis

## Preparation

```{r}
################################################################################
# Bassour
################################################################################
Bassour.1911.1912 <- Bassour.1911.1912|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Bassour.1911.1912$year,
                                              Bassour.1911.1912$month,
                                              Bassour.1911.1912$day,
                                              sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
Bassour.1911.1912 <- replace(Bassour.1911.1912, Bassour.1911.1912 == -999, NA)
################################################################################
# Calama
################################################################################


################################################################################
# Haraqua Hala
################################################################################


################################################################################
# Hump Mountain
################################################################################


################################################################################
# Montezuma
################################################################################
Montezuma.1920.1930 <- Montezuma.1920.1930|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Montezuma.1920.1930$year,
                                              Montezuma.1920.1930$month,
                                              Montezuma.1920.1930$day,
                                              sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))

Montezuma.1920.1930 <- replace(Montezuma.1920.1930, 
                                    Montezuma.1920.1930 == -999, NA)

################################################################################
# Mt. Whitney
################################################################################


################################################################################
# Mt. Wilson
################################################################################
Mt.Wilson.1905.1920 <- Mt.Wilson.1905.1920|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Mt.Wilson.1905.1920$year,
                                              Mt.Wilson.1905.1920$month,
                                              Mt.Wilson.1905.1920$day,
                                              sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
################################################################################
Mt.Wilson.1905.1906 <- Mt.Wilson.1905.1906|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Mt.Wilson.1905.1906$year,
                                            Mt.Wilson.1905.1906$month,
                                            Mt.Wilson.1905.1906$day,
                                            sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
################################################################################
Mt.Wilson.1909.1912 <- Mt.Wilson.1909.1912|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Mt.Wilson.1909.1912$year,
                                            Mt.Wilson.1909.1912$month,
                                            Mt.Wilson.1909.1912$day,
                                            sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
Mt.Wilson.1909.1912 <- replace(Mt.Wilson.1909.1912, Mt.Wilson.1909.1912 == -999, NA)
################################################################################
# Mt. Brukkaros
################################################################################
Mt.Brukkaros.1926.1930 <- Mt.Brukkaros.1926.1930|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Mt.Brukkaros.1926.1930$year,
                                            Mt.Brukkaros.1926.1930$month,
                                            Mt.Brukkaros.1926.1930$day,
                                            sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
Mt.Brukkaros.1926.1930 <- replace(Mt.Brukkaros.1926.1930, Mt.Brukkaros.1926.1930 == -999, NA)
################################################################################
# Table Mountain
################################################################################
Table.mountain.1925.1930 <- Table.mountain.1925.1930|>
  dplyr::mutate('Date' = lubridate::ymd(paste(Table.mountain.1925.1930$year,
                                              Table.mountain.1925.1930$month,
                                              Table.mountain.1925.1930$day,
                                              sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))

Table.mountain.1925.1930 <- replace(Table.mountain.1925.1930, 
                                    Table.mountain.1925.1930 == -999, NA)
################################################################################
# Washington
################################################################################
Washington.1902.1904 <- Washington.1902.1904|>
  dplyr::mutate('Date' = lubridate::ymd(paste(year, month, day, sep = ' ')))|>
  dplyr::select(-c('year', 'month', 'day'))
Washington.1902.1904 <- replace(Washington.1902.1904, Washington.1902.1904 == -999, NA)
################################################################################
Washington.1903.1907 <- Washington.1903.1907|>
dplyr::mutate('Date' = lubridate::ymd(paste(year, month, day, sep = ' ')))|>
dplyr::select(-c('year', 'month', 'day'))
Washington.1903.1907 <- replace(Washington.1903.1907, Washington.1903.1907 == -999, NA)
```

## Bassour

```{r}
Bassour.1911.1912|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
  levels = c("350", "400", "450", "500", "600", "700", 
             "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.1) +
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  ggplot2::annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date [year]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
################################################################################
# Zoom in
Bassour.1911.1912|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
  levels = c("350", "400", "450", "500", "600", "700", 
             "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  dplyr::filter(Date > as_date('1912-01-01') & Date < as_date('1913-01-01')) |>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.5) +
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  ggplot2::annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date [year]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
```

## Calama

## Haraqua Hala

## Hump Mountain

## Montezuma

```{r}
pdf('../analysis/montezuma.1920.1930.pdf',
    width = 8, height = 5)
Montezuma.1920.1930|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1924-02-15")), linetype = 'dotted') +
  annotate("text", x = as.Date("1924-02-15", format = '%Y-%m-%d'),
  y = 0, label= "Raikoke [1924-02-15]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
################################################################################
# Zoom in 
pdf('../analysis/montezuma.2923.raikoke.pdf',
    width = 8, height = 5)
Montezuma.1920.1930|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  dplyr::filter(Date > as_date('1923-01-01') & Date < as_date('1926-01-01')) |>
ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.5) +
  geom_vline(xintercept = as.numeric(as.Date("1924-02-15")), linetype = 'dotted') +
  annotate("text", x = as.Date("1924-02-15", format = '%Y-%m-%d'),
  y = 0, label= "Raikoke [1924-02-15]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date [year]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```

## Mt. Brukkaros

```{r}
Mt.Brukkaros.1926.1930|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.1) +
  labs(x = 'Date [year]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
```

## Mt.Whitney

## Mt. Wilson

```{r}
# overview
pdf('../analysis/Mt.Wilson.1905.1920.pdf',
    width = 8, height = 5)
Mt.Wilson.1905.1920|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.1) +
  geom_vline(xintercept = as.numeric(as.Date("1907-03-28")), linetype = 'dotted') +
  annotate("text", x = as.Date("1907-03-28", format = '%Y-%m-%d'),
  y = 0, label= "Ksudach [1907-03-28]", hjust = 0, vjust = -0.2, angle = 90) + 
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = 0, vjust = -0.2, angle = 90) +
  geom_vline(xintercept = as.numeric(as.Date("1918-10-12")), linetype = 'dotted') +
  annotate("text", x = as.Date("1918-10-12", format = '%Y-%m-%d'),
  y = 0, label= "Katla [1918-10-12]", hjust = 0, vjust = -0.2, angle = 90) +  
  labs(x = 'Date [year]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
################################################################################
# Zoom in 
pdf('../analysis/Mt.Wilson.1912.katmai.pdf',
    width = 8, height = 5)
Mt.Wilson.1905.1920|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  dplyr::filter(Date > as_date('1912-01-01') & Date < as_date('1913-01-01')) |>
ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.5) +
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Months [1912]', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```

### Boxplot

```{r}
pdf('../analysis/Boxplot_Mt.Wilson.pdf',
    width = 8, height = 5)
Mt.Wilson.1905.1920|>
  dplyr::rename('350' = transmission1....100.,
  '400' = transmission2....100.,
  '450' = transmission3....100.,
  '500' = transmission4....100.,
  '600' = transmission5....100.,
  '700' = transmission6....100.,
  '800' = transmission7....100.,
  '1000' = transmission8....100.,
  '1200' = transmission9....100.,
  '1600' = transmission10....100.)|>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable, levels = c("350", "400", "450", "500",
  "600", "700", "800", "1000", "1200", "1600"))) |>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  ggplot()+
  geom_boxplot(aes(x = variable, y = values),
  notch = TRUE, outlier.alpha = .1, outlier.colour = 'black') +
  stat_boxplot(aes(x = variable, y = values),
  geom='errorbar', linetype = 1, width = 0.8) +
  geom_jitter(aes(x = variable, y = values), size = .5, width = .1, alpha = .1)+
  labs(x = 'Wavelength [nm]', y = 'Transmittance [%]') +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off
```

```{r}
# optical depth
pdf('../analysis/Mt.Wilson.od.1905.1920.pdf',
    width = 8, height = 5)
Mt.Wilson.1905.1920|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  dplyr::mutate_at(c('350', '400','450', '500', '600', '700', 
                     '800', '1000', '1200', '1600'), ~-log(.))|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.5) +
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = -1.6, vjust = -0.2, angle = 90) +
  labs(x = 'Time [1905 - 1920]', y = 'Optical depth') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
###############################################################################################
pdf('../analysis/Mt.Wilson.od.1912.pdf',
    width = 8, height = 5)
Mt.Wilson.1905.1920|>
  dplyr::rename('350' = transmission1....100.,
                '400' = transmission2....100.,
                '450' = transmission3....100.,
                '500' = transmission4....100.,
                '600' = transmission5....100.,
                '700' = transmission6....100.,
                '800' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::mutate(Row = c(1 : length(Date))) |>
  dplyr::mutate_at(c('350', '400','450' ,'500', '600', '700', 
                     '800', '1000', '1200', '1600'), ~-log(.))|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                levels = c("350", "400", "450", "500", "600", "700", 
                           "800", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  dplyr::filter(Date > as_date('1912-01-01') & Date < as_date('1913-01-01')) |>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable), alpha = 0.5) +
  geom_vline(xintercept = as.numeric(as.Date("1912-06-06")), linetype = 'dotted') +
  annotate("text", x = as.Date("1912-06-06", format = '%Y-%m-%d'),
  y = 0, label= "Katmai [1912-06-06]", hjust = -1.6, vjust = -.2, angle = 90) +
  labs(x = 'Months [1912]', y = 'Optical depth') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```

```         
```

## Table Mountain

```{r}
Table.mountain.1925.1930|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1924-02-15")), linetype = 'dotted') +
  annotate("text", x = as.Date("1924-02-15", format = '%Y-%m-%d'),
  y = 0, label= "Raikoke [1924-02-15]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))



Table.mountain.1925.1930|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  dplyr::mutate_at(c('400', '450', '500', '600', '700', 
                     '800','900', '1000', '1200', '1600'), ~-log(.))|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  dplyr::mutate(values = ifelse(values >= 1, values/1000, values)) |>
  dplyr::mutate(values = ifelse(values <= 0.1, NA, values)) |>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1924-02-15")), linetype = 'dotted') +
  annotate("text", x = as.Date("1924-02-15", format = '%Y-%m-%d'),
  y = 0, label= "Raikoke [1924-02-15]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date', y = 'Optical depth') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
```

## Washington

```{r}
pdf('../analysis/washington.1902.1907.pdf',
    width = 8, height = 5)
Washington.1902.1904|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1902-10-26")), linetype = 'dotted') +
  annotate("text", x = as.Date("1902-10-26", format = '%Y-%m-%d'),
  y = 0, label= "Santa Maria [1902-10-26]", hjust = 0, vjust = -0.2, angle = 90) +
  geom_vline(xintercept = as.numeric(as.Date("1907-03-28")), linetype = 'dotted') +
    annotate("text", x = as.Date("1907-03-28", format = '%Y-%m-%d'),
  y = 0, label= "Ksudach [1907-03-28]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
###############################################################################################
pdf('../analysis/washington.1902.santamaria.pdf',
    width = 8, height = 5)
Washington.1902.1904|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  dplyr::filter(Date > as_date('1902-01-01') & Date < as_date('1904-01-01')) |>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1902-10-26")), linetype = 'dotted') +
  annotate("text", x = as.Date("1902-10-26", format = '%Y-%m-%d'),
  y = 0, label= "Santa Maria [1902-10-26]", hjust = 0, vjust = -0.2, angle = 90) +
  labs(x = 'Date', y = 'Transmittance [%]') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```

## 

```{r}
pdf('../analysis/washington.od.1902.1907.pdf',
    width = 8, height = 5)
Washington.1902.1904|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  dplyr::mutate_at(c('400', '450', '500', '600', '700', 
                     '800','900', '1000', '1200', '1600'), ~-log(.))|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1902-10-26")), linetype = 'dotted') +
  annotate("text", x = as.Date("1902-10-26", format = '%Y-%m-%d'),
  y = 0, label= "Santa Maria [1902-10-26]", hjust = -1, vjust = -0.2, angle = 90) +
  geom_vline(xintercept = as.numeric(as.Date("1907-03-28")), linetype = 'dotted') +
    annotate("text", x = as.Date("1907-03-28", format = '%Y-%m-%d'),
  y = 0, label= "Ksudach [1907-03-28]", hjust = -1, vjust = -0.2, angle = 90) +
  labs(x = 'Date [1902 - 1907]', y = 'Optical depth') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
###############################################################################################
pdf('../analysis/washington.od.1902.pdf',
    width = 8, height = 5)
Washington.1902.1904|>
  dplyr::rename('400' = transmission1....100.,
                '450' = transmission2....100.,
                '500' = transmission3....100.,
                '600' = transmission4....100.,
                '700' = transmission5....100.,
                '800' = transmission6....100.,
                '900' = transmission7....100.,
                '1000' = transmission8....100.,
                '1200' = transmission9....100.,
                '1600' = transmission10....100.) |>
  dplyr::select(ends_with('0'), Date)|>
  dplyr::mutate_at(c('400', '450', '500', '600', '700', 
                     '800','900', '1000', '1200', '1600'), ~-log(.))|>
  pivot_longer(cols = ends_with('0'),
               names_to = 'variable',
               values_to = 'values')|>
  dplyr::mutate(variable = factor(variable,
                                levels = c("400", "450", "500", "600", "700",
                                      "800", "900", "1000", "1200", "1600")))|>
  dplyr::filter(Date > as_date('1902-01-01') & Date < as_date('1904-01-01')) |>
  drop_na()|>
  ggplot()+
  geom_point(aes(x = Date, y = values, color = variable)) +
  geom_vline(xintercept = as.numeric(as.Date("1902-10-26")), linetype = 'dotted') +
  annotate("text", x = as.Date("1902-10-26", format = '%Y-%m-%d'),
  y = 0, label= "Santa Maria [1902-10-26]", hjust = -1, vjust = -0.2, angle = 90) +
  labs(x = 'Months [1902 - 1903]', y = 'Optical depth') +
  scale_color_viridis_d(option = "magma",
  guide = guide_legend(override.aes = list(size = 3,
  alpha = 1), title = "Wavelength [nm]")) +
  theme_light() +
  theme(panel.border = element_rect(colour = "black", fill = NA, linewidth = 1))
dev.off()
```
